import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

// works in only server side
export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Next.js Tutorial - Helloworld",
    template: "%s | Helloworld",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" h-full flex flex-col">
          <header className=" bg-lime-300 p-4 space-x-5">
            <p>header</p>
          </header>
          <div className=" flex-1">{children}</div>

          <footer className=" bg-rose-300 p-4 ">
            <p>footer</p>
          </footer>
        </div>
      </body>
    </html>
  );
}
